### ISSUE TITLE
Contest Rules Date iWalk V2 2021

### ISSUE THREAD

**Issue by KelsMarie** [sfbrigade/intentional-walk#159] opened 2021-06-02 06:26 UTC
*Contest Rules Date Change:
*Starts on August 1, 2021, at 12:00 AM PST.
*Ends at 11:59 p.m. PST on August 31, 2021.
*The top ten walkers will be notified the first week of September 2021 by email.

**Comment by ohrite** [comment] 2021-06-10 02:25
Duplicate of: https://github.com/sfbrigade/intentional-walk/issues/158

**Closed** 2021-06-10 02:25 UTC
